### ISSUE TITLE
请问一下怎样打开查看？

### ISSUE THREAD

**Issue by leongfeng** [TiriSane/Visually-Algorithm#1]
proj.win32文件夹下的文件运行不了

**Comment by TiriSane** [comment]
proj.win32文件夹下的文件是visual studio项目有关文件，要查看这个项目，首先你需要下载并配置cocos2dx 3.13.1的游戏引擎，再创建一个空项目，最后用这个项目里的proj.win32,Classes和Resources三个文件加夹替换你创建项目里的三个同名文件夹。这时候再点击proj.win32文件夹中的sln文件，你就可以查看的编译这个项目。因为游戏引擎太大，无法上传到github，因此需要你自己构建cocos项目。有关文档http://www.cocos.com/docs/native/v3/getting-started/setting-up-development-environments-on-windows7-with-vs2013/zh.html
